#!/usr/bin/env bash
# commit-attribution-guard.sh 的回歸測試（characterization）：git commit 帶 AI attribution 回 deny，其餘無輸出。
# 指令只以 JSON 字串餵給 hook，不會被執行。HOOK 可用環境變數覆寫（teeth check 用）。
set -u
HOOK=${HOOK:-"$(cd "$(dirname "$0")/.." && pwd)/commit-attribution-guard.sh"}
command -v jq >/dev/null 2>&1 || { echo "FAIL 需要 jq"; exit 1; }
fail=0; n=0
run() { # name expect(deny|none) command
  n=$((n + 1))
  out=$(jq -n --arg c "$3" '{tool_input:{command:$c}}' | bash "$HOOK" 2>/dev/null); rc=$?
  dec=$(printf '%s' "$out" | jq -r '.hookSpecificOutput.permissionDecision // empty' 2>/dev/null)
  text=$(printf '%s' "$out" | jq -r '.hookSpecificOutput.permissionDecisionReason // empty' 2>/dev/null)
  ok=0
  if [ "$2" = none ]; then [ -z "$out" ] && ok=1; else [ "$dec" = "$2" ] && printf '%s' "$text" | grep -q 'commit attribution guard' && ok=1; fi
  [ $rc = 0 ] || ok=0
  [ $ok = 1 ] || { echo "FAIL $1 expect=$2 rc=$rc dec=$dec out=$out"; fail=1; }
}
HEREDOC=$'git commit -m "$(cat <<\'EOF\'\nfix: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nEOF\n)"'

# --- 被攔：三種 attribution 字樣 ---
run coauthored_trailer deny 'git commit -m "feat: x

Co-Authored-By: Claude <noreply@anthropic.com>"'
run coauthored_heredoc deny "$HEREDOC"
run coauthored_lowercase deny 'git commit -m "x co-authored-by: bot"'
run coauthored_uppercase deny 'git commit -m "x CO-AUTHORED-BY: bot"'
run generated_by deny 'git commit -m "feat: x. Generated by Claude Code"'
run generated_by_lowercase deny 'git commit -m "generated by tool"'
run ai_assisted deny 'git commit -m "feat: x (AI-assisted)"'
run ai_assisted_lowercase deny 'git commit -m "ai-assisted refactor"'
run amend_with_attribution deny 'git commit --amend -m "x Generated by AI"'
run second_m_flag deny 'git commit -m "x" -m "AI-assisted"'
run after_add_and deny 'git add a.txt && git commit -m "x Co-Authored-By: bot"'
run after_semicolon deny 'cd r; git commit -m "x AI-assisted"'
run commit_all_flag deny 'git commit -am "x Generated by bot"'
run commit_bare_with_trailing_text deny 'git commit # Co-Authored-By: bot'
# GAP: 比對整條指令字串，commit 之後串的其他指令含這些字樣也會被攔
run attribution_in_other_command deny 'git commit -m "x" && echo "Generated by me"'
# GAP: 「Generated by」不分語境，正常 message（如 codegen 說明）會被誤攔
run generated_by_false_positive deny 'git commit -m "fix: file generated by codegen"'

# --- 放行：一般 commit ---
run plain_commit none 'git commit -m "fix: handle empty input"'
run multiline_commit none 'git commit -m "feat: x

Body line one.
Body line two."'
run amend_no_edit none 'git commit --amend --no-edit'
run commit_bare none 'git commit'
run commit_all none 'git commit -am "chore: bump"'
run commit_signoff none 'git commit -s -m "fix: x"'

# --- near-miss：commit 但字樣不完全符合 ---
run generated_code_phrase none 'git commit -m "chore: generated code cleanup"'
run generated_without_by none 'git commit -m "docs: generated docs"'
run coauthored_without_colon none 'git commit -m "docs: explain Co-Authored-By usage"'
run ai_assisted_space none 'git commit -m "docs: AI assisted workflow"'
run ai_word_only none 'git commit -m "feat: add AI router"'

# --- 放行：非 commit 指令含這些字 ---
run echo_trailer none 'echo "Co-Authored-By: bot"'
run log_grep_generated none 'git log --grep "Generated by"'
run log_grep_ai none 'git log --grep="AI-assisted" --oneline'
run commit_tree_hyphen none 'git commit-tree -m "Co-Authored-By: bot" HEAD^{tree}'
run grep_in_repo none 'rg "Generated by" src/'
run cat_file none 'cat AI-assisted.md'
run push_with_text none 'git push origin main # Co-Authored-By: bot'
# GAP: git 全域參數（-C）插在 commit 前面時比對不到，attribution 放行
run commit_with_dash_C none 'git -C repo commit -m "x Co-Authored-By: bot"'
# GAP: attribution 來自 -F / --template 檔案內容，hook 看不到
run commit_from_file none 'git commit -F msg.txt'

# --- 空輸入 ---
run empty_command none ''
for raw in '{"tool_input":{}}' 'not json'; do # stdin 不是預期格式：無輸出、exit 0
  n=$((n + 1))
  out=$(printf '%s' "$raw" | bash "$HOOK" 2>/dev/null); rc=$?
  { [ -z "$out" ] && [ $rc = 0 ]; } || { echo "FAIL raw_input '$raw' rc=$rc out=$out"; fail=1; }
done

[ $fail = 0 ] && echo "all passed ($n cases)"; exit $fail
