#!/usr/bin/env python3

import os
import sys
import subprocess

class InitDevTool:
    def __init__(self, project_name, project_type):
        self.project_name = project_name
        self.project_type = project_type

    def run_script(self):
        pass

    def create_dir(self, dir_name):
        try:
            os.mkdir(dir_name)
            os.chdir(dir_name)
        except FileExistsError:
            print(f'{dir_name} already exists, skipping...')
            os.chdir(dir_name)
        pass

    def init_python():
        create_directory('src')
        subprocess.run(['poetry', 'init', '--no-interaction'])

    def init_nodejs():
        subprocess.run(['npm', 'init', '-y'])
        subprocess.run(['npm', 'install', 'typescript', '--save-dev'])
        create_directory('src')
        create_file('tsconfig.json', '{"compilerOptions": {"target": "es6"}}')

    def init_git():
        subprocess.run(['git', 'init'])
        create_file('.gitignore', "*.pyc\n__pycache__\n.env\n")
        create_file('.env')
        subprocess.run(['git', 'add', '.'])
        subprocess.run(['git', 'commit', '-m', 'Initial commit'])

def main():
    print('Project initializing...')
    args: list = sys.argv

    print('Project initializing complete')
    pass

if __name__=='__main__':
    main()