#!/usr/bin/env bash

if ! command -v jq >/dev/null 2>&1; then
  exit 0
fi

input=$(cat)
cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // empty')

[ -z "$cmd" ] && exit 0

if ! printf '%s\n' "$cmd" | grep -Eq '(^|[;&|[:space:]])git[[:space:]]+commit([[:space:]]|$)'; then
  exit 0
fi

if ! printf '%s\n' "$cmd" | grep -Eqi 'Co-Authored-By:|Generated by|AI-assisted'; then
  exit 0
fi

jq -n '{
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "permissionDecision": "deny",
    "permissionDecisionReason": "commit attribution guard: remove AI attribution text from the commit message"
  }
}'
